---
title: "Final Project"
author: "Shaun Donmoyer"
date: "10/23/2019"
output: html_document
---

# Load appropriate library

```{r}
library(odbc)
library(data.table)
```

#Connect to database
```{r}
con <- dbConnect(odbc(),Driver="SQL Server",Server="localhost\\SQLEXPRESS", Database="FracFocusRegistry", Trusted_Connection="True") 
```

#Retreives all disclosures from Regisitry Upload Purpose
```{r}
RUP <- data.table(dbGetQuery(con, "SELECT * FROM [FracFocusRegistry].[dbo].[RegistryUploadPurpose]"))
```


# Function for any Ingredient Purpose

```{r}
library(ggplot2)
library(dplyr)
```

  

## This is the funtion for any ingredient purpose and plot its freq as bar plot.

```{r}
test <- function(purpose){
  
  if (!is.character(purpose)) {
    stop("Purpose must be a character vector.")
   }
  
  
  data <- RUP[which(RUP$Purpose == purpose), "TradeName" ]
  count_data <- data %>% 
    count(TradeName, sort = TRUE)
  count_data <- count_data[c(1:10), ]
    
  plot_title <- paste("10 most used", purpose, "in FracFocus")
    New_Plot <- ggplot(count_data, aes(x=TradeName, y=n)) + geom_bar(stat="identity", color="blue",fill="white") + 
     labs(x="TradeName", y="Frequency",title=plot_title) +geom_text(aes(label=n), vjust=1.6, color="black", size=3.5)+theme(axis.text.x=element_text(size=10,angle=45,hjust=1,vjust=1))

New_Plot
}
```



## Function to summarize any ingredient

```{r}
library(dplyr)
library(kableExtra)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
RUI <- data.table(dbGetQuery(con, "SELECT [IngredientName],[PercentHFJob] FROM [FracFocusRegistry].[dbo].[RegistryUploadIngredients]"))
```

```{r}
new_RUI <- RUI %>%
  
  filter(PercentHFJob != "0", PercentHFJob < "30")
```



```{r}
ing_report <- function(ingredient){
  
  
ing_name <- paste(ingredient)


  ing_summary <- new_RUI %>%
  
  filter(IngredientName == ing_name) %>%
  
  summarize(MeanWtPercent = mean(PercentHFJob, na.rm = TRUE), Minimum = min(PercentHFJob, na.rm=TRUE), Maximum = max(PercentHFJob, na.rm = TRUE), Count = n(), Quan10 = quantile(PercentHFJob, .1, na.rm = TRUE), Quan30 = quantile(PercentHFJob, .3, na.rm =TRUE), Quan50 = quantile(PercentHFJob, .5, na.rm = TRUE), Quan80 = quantile(PercentHFJob, .8, na.rm = TRUE))

names(ing_summary)[names(ing_summary) == "MeanWtPercent"] <- "Mean Wt %"
names(ing_summary)[names(ing_summary) == "Quan10"] <- "10th Percentile"
names(ing_summary)[names(ing_summary) == "Quan30"] <- "30th Percentile"
names(ing_summary)[names(ing_summary) == "Quan50"] <- "50th Percentile"
names(ing_summary)[names(ing_summary) == "Quan80"] <- "80th Percentile"

table_title <- paste("Ingredient Summary Report for", ing_name)

new_table <- ing_summary %>%
  kable(digits = 10, caption = table_title, booktabs = TRUE) %>%
  kable_styling()

return(new_table)
  
}

```


